let numero1 = 10;
let numero2 = 2;
const sumaNumero = numero1+numero2;
console.log('Resultado de la Suma es ' + sumaNumero);
const RestaNumero = numero1-numero2;
console.log('Resultado de la Resta es ' + RestaNumero);
const MultiplicarNumero = numero1*numero2;
console.log('Resultado de la Multiplicaión es ' + MultiplicarNumero);
const DividirNumero = numero1/numero2;
console.log('Resultado de la División es ' + DividirNumero);